name: bz_quiz
description: Quiz app about B'z

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # added
  cupertino_icons: ^0.1.3
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6
  flutter_launcher_icons: ^0.7.5
  fluttertoast: ^4.0.1
  soundpool: ^1.1.1
  provider: ^4.1.3
  flutter_spinkit: ^4.1.2+1
  firebase_crashlytics: ^0.1.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/sounds/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"


